const AnalysisReport = [
  {
    id: 1,
    date: "2025-02-05",
    text: "I feel so exhausted and empty all the time.",
    depression_percentage: 85,
    non_depression_percentage: 15,
  },
  {
    id: 2,
    date: "2025-02-04",
    text: "Life has been really hard lately, I don’t know how to cope.",
    depression_percentage: 78,
    non_depression_percentage: 22,
  },
  {
    id: 3,
    date: "2025-02-03",
    text: "I'm okay, just tired from work.",
    depression_percentage: 10,
    non_depression_percentage: 90,
  },
  {
    id: 4,
    date: "2025-02-02",
    text: "I have lost interest in things I used to love.",
    depression_percentage: 82,
    non_depression_percentage: 18,
  },
  {
    id: 5,
    date: "2025-02-01",
    text: "Had a great time with friends today!",
    depression_percentage: 5,
    non_depression_percentage: 95,
  },
  {
    id: 6,
    date: "2025-01-31",
    text: "I can't sleep at night, my mind keeps racing.",
    depression_percentage: 76,
    non_depression_percentage: 24,
  },
  {
    id: 7,
    date: "2025-01-30",
    text: "Feeling hopeless and worthless lately.",
    depression_percentage: 88,
    non_depression_percentage: 12,
  },
  {
    id: 8,
    date: "2025-01-29",
    text: "Work is stressful but I’m managing.",
    depression_percentage: 20,
    non_depression_percentage: 80,
  },
  {
    id: 9,
    date: "2025-01-28",
    text: "I don’t see the point in anything anymore.",
    depression_percentage: 90,
    non_depression_percentage: 10,
  },
  {
    id: 10,
    date: "2025-01-27",
    text: "Just finished a great book, feeling inspired!",
    depression_percentage: 8,
    non_depression_percentage: 92,
  },
  {
    id: 11,
    date: "2025-01-26",
    text: "I'm constantly feeling down, and nothing helps.",
    depression_percentage: 84,
    non_depression_percentage: 16,
  },
  {
    id: 12,
    date: "2025-01-25",
    text: "I don’t feel like getting out of bed anymore.",
    depression_percentage: 92,
    non_depression_percentage: 8,
  },
  {
    id: 13,
    date: "2025-01-24",
    text: "Had a good day at work today.",
    depression_percentage: 12,
    non_depression_percentage: 88,
  },
  {
    id: 14,
    date: "2025-01-23",
    text: "I feel like I’m drowning in my thoughts.",
    depression_percentage: 87,
    non_depression_percentage: 13,
  },
  {
    id: 15,
    date: "2025-01-22",
    text: "Feeling a little better today, hope it lasts.",
    depression_percentage: 35,
    non_depression_percentage: 65,
  },
  {
    id: 16,
    date: "2025-01-21",
    text: "No motivation to do anything anymore.",
    depression_percentage: 91,
    non_depression_percentage: 9,
  },
  {
    id: 17,
    date: "2025-01-20",
    text: "I had a fun weekend with my family!",
    depression_percentage: 6,
    non_depression_percentage: 94,
  },
  {
    id: 18,
    date: "2025-01-19",
    text: "I feel completely alone in this world.",
    depression_percentage: 93,
    non_depression_percentage: 7,
  },
  {
    id: 19,
    date: "2025-01-18",
    text: "Trying to stay positive, but it’s hard.",
    depression_percentage: 40,
    non_depression_percentage: 60,
  },
  {
    id: 20,
    date: "2025-01-17",
    text: "Today was an amazing day!",
    depression_percentage: 3,
    non_depression_percentage: 97,
  },
];

export default AnalysisReport;
